# Generated by Django 3.2.23 on 2025-02-19 01:40

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fuelstation',
            index=django.contrib.postgres.indexes.GistIndex(fields=['location'], name='route_plann_locatio_cc9c61_gist'),
        ),
    ]
